version: '3'
services:
  pulsar:
    container_name: pulsar
    command: bin/pulsar standalone
    image: apachepulsar/pulsar:latest
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      - local-pulsar-net
networks:
  local-pulsar-net:
